# Ćwiczenia

## Ćwiczenie 1. - NumPy

#### Rozwiązanie

In [1]:
import numpy as np

# Stworzenie dwuwymiarowej tablicy
tablica_2d_cw = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Zadanie: Pomnóż każdy element tablicy przez 2
wynik_mnozenia_cw = tablica_2d_cw * 2

# Zadanie: Oblicz średnią dla każdej kolumny
srednia_kolumn_cw = np.mean(tablica_2d_cw, axis=0)

# Wyświetlenie wyników
print("Tablica po mnożeniu przez 2:")
print(wynik_mnozenia_cw)

print("\nŚrednie kolumn:")
print(srednia_kolumn_cw)

Tablica po mnożeniu przez 2:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Średnie kolumn:
[4. 5. 6.]


#### Omówienie

## Ćwiczenie 2. - Pandas

#### Rozwiązanie:

In [2]:
import pandas as pd
import numpy as np

# Stworzenie DataFrame z danymi losowymi
df_cw = pd.DataFrame(np.random.randint(0, 100, size=(5, 3)), columns=['A', 'B', 'C'])

# Wyświetlenie informacji o danych w DataFrame
info_dane_cw = df_cw.info()

# Wyświetlenie trzech pierwszych wierszy DataFrame
pierwsze_wiersze_cw = df_cw.head(3)

# Wyświetlenie wyników
print("Informacje o danych:", info_dane_cw)
print("Trzy pierwsze wiersze DataFrame:\n", pierwsze_wiersze_cw)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int32
 1   B       5 non-null      int32
 2   C       5 non-null      int32
dtypes: int32(3)
memory usage: 192.0 bytes
Informacje o danych: None
Trzy pierwsze wiersze DataFrame:
     A   B   C
0  37  94  36
1  10  22  55
2  60  81  21


#### Omówienie

## Ćwiczenie 3. - Wczytywanie i zapis danych

#### Rozwiązanie

In [3]:
import pandas as pd

# Wczytanie danych z pliku CSV
df_wczytane_cw = pd.read_csv('../DayTwo/top_100_world_university_2024_new.csv')

# Wyświetlenie pięciu pierwszych wierszy wczytanych danych
pierwsze_wiersze_wczytane_cw = df_wczytane_cw.head()

# Zapisanie wczytanych danych do pliku Excel
df_wczytane_cw.to_excel('dane_wczytane_top_universities.xlsx', index=False)

#### Omówienie

## Ćwiczenie 4. - Atrybuty DataFrame w Pandas

#### Rozwiązanie

In [4]:
import pandas as pd

# Ćwiczenie: Sprawdzenie kształtu i struktury DataFrame
df_cw = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

# Zadanie: Wyświetlenie kształtu DataFrame
ksztalt_cw = df_cw.shape

# Zadanie: Wyświetlenie indeksów wierszy DataFrame
indeksy_cw = df_cw.index

# Zadanie: Wyświetlenie etykiet kolumn DataFrame
etykiety_kolumn_cw = df_cw.columns

# Zadanie: Wyświetlenie typów danych kolumn DataFrame
typy_danych_cw = df_cw.dtypes

# Wyświetlenie wyników
print("Kształt DataFrame:", ksztalt_cw)
print("Indeksy wierszy DataFrame:", indeksy_cw)
print("Etykiety kolumn DataFrame:", etykiety_kolumn_cw)
print("Typy danych kolumn DataFrame:\n", typy_danych_cw)

Kształt DataFrame: (3, 2)
Indeksy wierszy DataFrame: RangeIndex(start=0, stop=3, step=1)
Etykiety kolumn DataFrame: Index(['A', 'B'], dtype='object')
Typy danych kolumn DataFrame:
 A    int64
B    int64
dtype: object


## Ćwiczenie 5. - Przydatne funkcje w Pandas

#### Rozwiązanie

In [5]:
# Rozwiązanie: Użycie funkcji describe, info, head, tail, sample
df_cw = pd.DataFrame({'A': [1, 2, 3, 4, 5],
                      'B': ['a', 'b', 'c', 'd', 'e'],
                      'C': [0.1, 0.5, 0.8, 0.3, 0.9]})

# Opis statystyczny dla DataFrame
opis_statystyczny_cw = df_cw.describe()

# Informacje o danych w DataFrame
informacje_o_danych_cw = df_cw.info()

# Trzy pierwsze wiersze DataFrame
pierwsze_wiersze_cw = df_cw.head(3)

# Trzy ostatnie wiersze DataFrame
ostatnie_wiersze_cw = df_cw.tail(3)

# Trzy losowe wiersze DataFrame
losowe_wiersze_cw = df_cw.sample(3)

# Wyświetlenie wyników
print("Opis statystyczny DataFrame:\n", opis_statystyczny_cw)
print("\nInformacje o danych w DataFrame:\n", informacje_o_danych_cw)
print("\nTrzy pierwsze wiersze DataFrame:\n", pierwsze_wiersze_cw)
print("\nTrzy ostatnie wiersze DataFrame:\n", ostatnie_wiersze_cw)
print("\nTrzy losowe wiersze DataFrame:\n", losowe_wiersze_cw)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       5 non-null      int64  
 1   B       5 non-null      object 
 2   C       5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes
Opis statystyczny DataFrame:
               A         C
count  5.000000  5.000000
mean   3.000000  0.520000
std    1.581139  0.334664
min    1.000000  0.100000
25%    2.000000  0.300000
50%    3.000000  0.500000
75%    4.000000  0.800000
max    5.000000  0.900000

Informacje o danych w DataFrame:
 None

Trzy pierwsze wiersze DataFrame:
    A  B    C
0  1  a  0.1
1  2  b  0.5
2  3  c  0.8

Trzy ostatnie wiersze DataFrame:
    A  B    C
2  3  c  0.8
3  4  d  0.3
4  5  e  0.9

Trzy losowe wiersze DataFrame:
    A  B    C
4  5  e  0.9
1  2  b  0.5
3  4  d  0.3


## Ćwiczenie 6. - Czyszczenie Wartości Zduplikowanych w Pandas

#### Rozwiązanie

In [6]:
import pandas as pd

# Przykładowe utworzenie DataFrame
df_cw = pd.DataFrame({'A': [1, 2, 2, 3, 4],
                      'B': ['a', 'b', 'b', 'c', 'd']})

# Sprawdzenie duplikatów w całych wierszach
duplikaty_wiersze_cw = df_cw.duplicated()

# Sprawdzenie duplikatów w kolumnie 'A'
duplikaty_kolumna_A_cw = df_cw['A'].duplicated()

# Usunięcie zduplikowanych wierszy
df_bez_duplikatow_cw = df_cw.drop_duplicates()

# Usunięcie zduplikowanych wierszy bazując na kolumnie 'A'
df_bez_duplikatow_kolumna_A_cw = df_cw.drop_duplicates(subset='A')

# Wyświetlenie wyników
print("Duplikaty wierszy:\n", duplikaty_wiersze_cw)
print("Duplikaty w kolumnie 'A':\n", duplikaty_kolumna_A_cw)
print("DataFrame bez duplikatów:\n", df_bez_duplikatow_cw)
print("DataFrame bez duplikatów w kolumnie 'A':\n", df_bez_duplikatow_kolumna_A_cw)

Duplikaty wierszy:
 0    False
1    False
2     True
3    False
4    False
dtype: bool
Duplikaty w kolumnie 'A':
 0    False
1    False
2     True
3    False
4    False
Name: A, dtype: bool
DataFrame bez duplikatów:
    A  B
0  1  a
1  2  b
3  3  c
4  4  d
DataFrame bez duplikatów w kolumnie 'A':
    A  B
0  1  a
1  2  b
3  3  c
4  4  d


## Ćwiczenie 7. - Wartości Brakujące - Różne Podejścia do Radzenia Sobie z Nimi w Pandas

#### Rozwiązanie

In [7]:
# Rozwiązanie: Radzenie sobie z wartościami brakującymi
df_cw = pd.DataFrame({'A': [1, 2, None, 4],
                      'B': ['a', 'b', 'c', None]})

# Sprawdzenie wartości brakujących w DataFrame
brakujace_wartosci_cw = df_cw.isnull()

# Usunięcie wierszy zawierających wartości brakujące
df_bez_brakujacych_wierszy_cw = df_cw.dropna()

# Uzupełnienie wartości brakujących w kolumnie 'A' średnią wartością
srednia_wartosc_A_cw = df_cw['A'].mean()
df_uzupelnione_cw = df_cw.fillna({'A': srednia_wartosc_A_cw, 'B': 'brak_danych'})

# Wyświetlenie wyników
print("Wartości brakujące w DataFrame:\n", brakujace_wartosci_cw)
print("DataFrame bez wierszy zawierających wartości brakujące:\n", df_bez_brakujacych_wierszy_cw)
print("DataFrame po uzupełnieniu wartości brakujących:\n", df_uzupelnione_cw)

Wartości brakujące w DataFrame:
        A      B
0  False  False
1  False  False
2   True  False
3  False   True
DataFrame bez wierszy zawierających wartości brakujące:
      A  B
0  1.0  a
1  2.0  b
DataFrame po uzupełnieniu wartości brakujących:
           A            B
0  1.000000            a
1  2.000000            b
2  2.333333            c
3  4.000000  brak_danych


## Ćwiczenie 8. - Wykrywanie Wartości Odstających w Pandas

#### Rozwiązanie

In [8]:
# Rozwiązanie: Wykrywanie i radzenie sobie z wartościami odstającymi

import pandas as pd

# Przykładowe utworzenie DataFrame z wartościami odstającymi
data = {'A': [1, 2, 3, 100],
        'B': [4, 5, 6, 200]}
df_cw = pd.DataFrame(data)

# Wykrycie wartości odstających na podstawie kwantyli
kwantyl_25_cw = df_cw.quantile(0.25)
kwantyl_75_cw = df_cw.quantile(0.75)
rozstep_miedzykwartylowy_cw = kwantyl_75_cw - kwantyl_25_cw

# Definiowanie zakresu wartości "normalnych"
dolny_limit_cw = kwantyl_25_cw - 1.5 * rozstep_miedzykwartylowy_cw
gorny_limit_cw = kwantyl_75_cw + 1.5 * rozstep_miedzykwartylowy_cw

# Wykrywanie wartości odstających
odstajace_wartosci_cw = (df_cw < dolny_limit_cw) | (df_cw > gorny_limit_cw)

# Zastępowanie wartości odstających wartością graniczną
df_bez_odstajacych_cw = df_cw.mask(odstajace_wartosci_cw, gorny_limit_cw, axis=1)

# Wyświetlenie wyników
print("Wartości odstające w DataFrame:\n", odstajace_wartosci_cw)
print("DataFrame po zastąpieniu wartości odstających:\n", df_bez_odstajacych_cw)

Wartości odstające w DataFrame:
        A      B
0  False  False
1  False  False
2  False  False
3   True   True
DataFrame po zastąpieniu wartości odstających:
       A        B
0   1.0    4.000
1   2.0    5.000
2   3.0    6.000
3  65.5  129.125


## Ćwiczenie 9. - Sortowanie Danych w Pandas

#### Rozwiązanie

In [9]:
# Rozwiązanie Ćwiczenia: Sortowanie danych w Pandas
df_cw = pd.DataFrame({'A': [3, 1, 4, 2],
                      'B': ['c', 'a', 'd', 'b']})

# Zadanie: Sortowanie wierszy według kolumny 'A'
df_posortowany_cw = df_cw.sort_values(by='A')

# Zadanie: Sortowanie kolumn według etykiet
df_kolumny_posortowane_cw = df_cw.sort_index(axis=1)

# Zadanie: Sortowanie wierszy malejąco według kolumny 'A'
df_posortowany_malejaco_cw = df_cw.sort_values(by='A', ascending=False)

# Wyświetlenie wyników
print("DataFrame po posortowaniu wierszy według kolumny 'A':\n", df_posortowany_cw)
print("DataFrame po posortowaniu kolumn według etykiet:\n", df_kolumny_posortowane_cw)
print("DataFrame po posortowaniu malejąco według kolumny 'A':\n", df_posortowany_malejaco_cw)

DataFrame po posortowaniu wierszy według kolumny 'A':
    A  B
1  1  a
3  2  b
0  3  c
2  4  d
DataFrame po posortowaniu kolumn według etykiet:
    A  B
0  3  c
1  1  a
2  4  d
3  2  b
DataFrame po posortowaniu malejąco według kolumny 'A':
    A  B
2  4  d
0  3  c
3  2  b
1  1  a


## Ćwiczenie 10. - Filtrowanie Danych w Pandas

#### Rozwiązanie

In [10]:
# Rozwiązanie: Filtrowanie danych w Pandas
df_cw = pd.DataFrame({'A': [1, 2, 3, 4],
                      'B': ['a', 'b', 'c', 'd']}, index=['x', 'y', 'z', 'w'])

# Filtrowanie wierszy o indeksach 'x' i 'y' oraz kolumny 'A'
df_filtr_loc_cw = df_cw.loc[['x', 'y'], 'A']

# Filtrowanie pierwszych dwóch wierszy oraz pierwszej kolumny za pomocą ilocdf_cw
df_filtr_iloc_cw = df_cw.iloc[:2, 0]

# Filtrowanie wierszy, gdzie wartość w kolumnie 'A' jest większa niż 2 za pomocą query
df_filtr_query_cw = df_cw.query('A > 2')

# Filtrowanie, zwracając nowy DataFrame z wartościami, które spełniają warunek, a reszta to NaN za pomocą where
df_filtr_where_cw = df_cw.where(df_cw['A'] > 2)

# Filtrowanie wierszy, gdzie wartość w kolumnie 'B' jest jedną z określonych wartości za pomocą isin
df_filtr_isin_cw = df_cw[df_cw['B'].isin(['a', 'c'])]

# Filtrowanie wierszy, gdzie wartość w kolumnie 'A' jest NaN za pomocą isnull
df_filtr_isnull_cw = df_cw[df_cw['A'].isnull()]

# Filtrowanie wierszy, gdzie wartość w kolumnie 'A' nie jest NaN za pomocą notnull
df_filtr_notnull_cw = df_cw[df_cw['A'].notnull()]

# Wyświetlenie wyników
print("Wynik filtrowania za pomocą loc:\n", df_filtr_loc_cw, '\n\n----------------------\n')
print("Wynik filtrowania za pomocą iloc:\n", df_filtr_iloc_cw, '\n\n----------------------\n')
print("Wynik filtrowania za pomocą query:\n", df_filtr_query_cw, '\n\n----------------------\n')
print("Wynik filtrowania za pomocą where:\n", df_filtr_where_cw, '\n\n----------------------\n')
print("Wynik filtrowania za pomocą isin:\n", df_filtr_isin_cw, '\n\n----------------------\n')
print("Wynik filtrowania za pomocą isnull:\n", df_filtr_isnull_cw, '\n\n----------------------\n')
print("Wynik filtrowania za pomocą notnull:\n", df_filtr_notnull_cw, '\n\n----------------------\n')

Wynik filtrowania za pomocą loc:
 x    1
y    2
Name: A, dtype: int64 

----------------------

Wynik filtrowania za pomocą iloc:
 x    1
y    2
Name: A, dtype: int64 

----------------------

Wynik filtrowania za pomocą query:
    A  B
z  3  c
w  4  d 

----------------------

Wynik filtrowania za pomocą where:
      A    B
x  NaN  NaN
y  NaN  NaN
z  3.0    c
w  4.0    d 

----------------------

Wynik filtrowania za pomocą isin:
    A  B
x  1  a
z  3  c 

----------------------

Wynik filtrowania za pomocą isnull:
 Empty DataFrame
Columns: [A, B]
Index: [] 

----------------------

Wynik filtrowania za pomocą notnull:
    A  B
x  1  a
y  2  b
z  3  c
w  4  d 

----------------------



## Ćwiczenie 11. - Tabele Przestawne w Pandas

#### Rozwiązanie

In [11]:
# Rozwiązanie: Tworzenie tabeli przestawnej w Pandas
df_cw = pd.DataFrame({'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
                      'Value': [10, 20, 30, 40, 50, 60]})

# Tworzenie tabeli przestawnej
table_przestawna_cw = pd.pivot_table(df_cw, values='Value', columns='Category', aggfunc='sum')

# Określanie indeksów i kolumn dla tabeli przestawnej
table_przestawna_indeks_kolumny_cw = pd.pivot_table(df_cw, values='Value', index='Category', columns='Category', aggfunc='sum')

# Określanie funkcji agregującej (np. suma) dla tabeli przestawnej
table_przestawna_suma_cw = pd.pivot_table(df_cw, values='Value', index='Category', aggfunc='sum')

# Uzupełnianie wartości brakujących w tabeli przestawnej (np. wartością 0)
table_przestawna_uzupelniona_cw = pd.pivot_table(df_cw, values='Value', index='Category', fill_value=0, aggfunc='sum')

# Wyświetlenie wyników
print("Tabela przestawna:\n", table_przestawna_cw)
print("Tabela przestawna z określonymi indeksami i kolumnami:\n", table_przestawna_indeks_kolumny_cw, '\n\n----------------------\n')
print("Tabela przestawna z określoną funkcją agregującą (suma):\n", table_przestawna_suma_cw, '\n\n----------------------\n')
print("Tabela przestawna z uzupełnionymi wartościami brakującymi:\n", table_przestawna_uzupelniona_cw, '\n\n----------------------\n')

Tabela przestawna:
 Category   A    B
Value     90  120
Tabela przestawna z określonymi indeksami i kolumnami:
 Category     A      B
Category             
A         90.0    NaN
B          NaN  120.0 

----------------------

Tabela przestawna z określoną funkcją agregującą (suma):
           Value
Category       
A            90
B           120 

----------------------

Tabela przestawna z uzupełnionymi wartościami brakującymi:
           Value
Category       
A            90
B           120 

----------------------



## Ćwiczenie 12. - Grupowanie Danych w Pandas

#### Rozwiązanie

In [12]:
# Rozwiązanie Ćwiczenia: Grupowanie danych w Pandas
df_cw = pd.DataFrame({'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
                      'Value': [10, 20, 30, 40, 50, 60]})

# Zadanie: Grupowanie na podstawie kolumny 'Category' i obliczanie sumy dla każdej grupy
grupowanie_jedna_kolumna_cw = df_cw.groupby('Category').sum()

# Zadanie: Grupowanie na podstawie wielu kolumn i obliczanie sumy dla każdej grupy
grupowanie_wiele_kolumn_cw = df_cw.groupby(['Category', 'Value']).size().reset_index(name='Count')

# Zadanie: Grupowanie i obliczanie różnych statystyk dla każdej grupy
grupowanie_statystyki_cw = df_cw.groupby('Category').agg({'Value': ['sum', 'mean', 'count']})

# Wyświetlenie wyników
print("Wynik grupowania na podstawie jednej kolumny:\n", grupowanie_jedna_kolumna_cw, '\n\n----------------------\n')
print("Wynik grupowania na podstawie wielu kolumn:\n", grupowanie_wiele_kolumn_cw, '\n\n----------------------\n')
print("Wynik grupowania z różnymi operacjami dla każdej grupy:\n", grupowanie_statystyki_cw, '\n\n----------------------\n')

Wynik grupowania na podstawie jednej kolumny:
           Value
Category       
A            90
B           120 

----------------------

Wynik grupowania na podstawie wielu kolumn:
   Category  Value  Count
0        A     10      1
1        A     30      1
2        A     50      1
3        B     20      1
4        B     40      1
5        B     60      1 

----------------------

Wynik grupowania z różnymi operacjami dla każdej grupy:
          Value            
           sum  mean count
Category                  
A           90  30.0     3
B          120  40.0     3 

----------------------



## Ćwiczenie 13. - Łączenie Danych w Pandas

#### Rozwiązanie

In [14]:
# Rozwiązanie: Łączenie danych w Pandas
df1_cw = pd.DataFrame({'ID': [1, 2, 3],
                       'Value1': ['A', 'B', 'C']})

df2_cw = pd.DataFrame({'ID': [2, 3, 4],
                       'Value2': ['X', 'Y', 'Z']})

# Rozwiązanie: Łączenie na podstawie wspólnej kolumny 'ID'
laczenie_kolumna_cw = pd.merge(df1_cw, df2_cw, on='ID')

# Przykładowe utworzenie DataFrame'ów do łączenia na podstawie indeksu
df3_cw = pd.DataFrame({'Value3': ['M', 'N', 'O']}, index=[1, 2, 3])

# Rozwiązanie: Łączenie na podstawie wspólnego indeksu
laczenie_indeks_cw = pd.concat([df1_cw, df3_cw], axis=1)

# Rozwiązanie: Łączenie na podstawie wspólnego indeksu w kierunku pionowym
laczenie_pionowe_cw = pd.concat([df1_cw, df3_cw], axis=0)

# Wyświetlenie wyników
print("Wynik łączenia na podstawie wspólnej kolumny:\n", laczenie_kolumna_cw, '\n\n----------------------\n')
print("Wynik łączenia na podstawie wspólnego indeksu:\n", laczenie_indeks_cw, '\n\n----------------------\n')
print("Wynik łączenia na podstawie wspólnego indeksu w kierunku pionowym:\n", laczenie_pionowe_cw, '\n\n----------------------\n')

Wynik łączenia na podstawie wspólnej kolumny:
    ID Value1 Value2
0   2      B      X
1   3      C      Y 

----------------------

Wynik łączenia na podstawie wspólnego indeksu:
     ID Value1 Value3
0  1.0      A    NaN
1  2.0      B      M
2  3.0      C      N
3  NaN    NaN      O 

----------------------

Wynik łączenia na podstawie wspólnego indeksu w kierunku pionowym:
     ID Value1 Value3
0  1.0      A    NaN
1  2.0      B    NaN
2  3.0      C    NaN
1  NaN    NaN      M
2  NaN    NaN      N
3  NaN    NaN      O 

----------------------



## Ćwiczenie 14. - Tworzenie Nowych Atrybutów w Pandas

#### Rozwiązanie

In [15]:
# Rozwiązanie: Tworzenie nowych atrybutów w Pandas
df_cw = pd.DataFrame({'Value1': [10, 20, 30],
                      'Value2': [5, 15, 25]})

# Dodaj nowy atrybut 'Multiply' na podstawie iloczynu istniejących kolumn
df_cw['Multiply'] = df_cw['Value1'] * df_cw['Value2']

# Dodaj nowy atrybut 'Status' na podstawie warunku logicznego (np. > 50)
df_cw['Status'] = ['High' if x > 50 else 'Low' for x in df_cw['Multiply']]

# Utwórz nowy atrybut 'Grade' przy użyciu funkcji (np. A, B, C)
def categorize_grade(multiply_value):
    if multiply_value > 500:
        return 'A'
    elif multiply_value > 200:
        return 'B'
    else:
        return 'C'

df_cw['Grade'] = df_cw['Multiply'].apply(categorize_grade)

# Wyświetlenie wyników
print("DataFrame z dodanym atrybutem 'Multiply':\n", df_cw, '\n\n----------------------\n')
print("DataFrame z dodanym atrybutem 'Status':\n", df_cw, '\n\n----------------------\n')
print("DataFrame z dodanym atrybutem 'Grade':\n", df_cw, '\n\n----------------------\n')

DataFrame z dodanym atrybutem 'Multiply':
    Value1  Value2  Multiply Status Grade
0      10       5        50    Low     C
1      20      15       300   High     B
2      30      25       750   High     A 

----------------------

DataFrame z dodanym atrybutem 'Status':
    Value1  Value2  Multiply Status Grade
0      10       5        50    Low     C
1      20      15       300   High     B
2      30      25       750   High     A 

----------------------

DataFrame z dodanym atrybutem 'Grade':
    Value1  Value2  Multiply Status Grade
0      10       5        50    Low     C
1      20      15       300   High     B
2      30      25       750   High     A 

----------------------

